apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-api
  namespace: production
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.simpleapp.pro 
    http:
      paths:
      - path: /
        backend:
          serviceName: simple-api
          servicePort: 1500